#!/bin/bash
#
# Copyright (c) 2010 Miro Bezjak <bezjak.miro@gmail.com>
#
# Licensed under the MIT License (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.opensource.org/licenses/mit-license.php
#

set -o errexit

NAPALM_VERSION=0.1
NAPALM_HOME=$(dirname $(readlink -f $0))

# error codes
E_USAGE=10

###################
# print functions #

# print usage to stderr and exit with E_USAGE
print_usage() {
cat >&2 << EOF
napalm - not a real package manager

SYNOPSIS
    napalm install NAME VERSION
    napalm use NAME [VERSION]
    napalm show [NAME [VERSION]]
    napalm create-plugin NAME
    napalm list-plugins
    napalm -h
    napalm -v

NAME    - program name
VERSION - program version
EOF

exit $E_USAGE
}

# print version to stderr and exit
print_version() {
cat >&2 << EOF
napalm $NAPALM_VERSION
Copyright (c) 2010 Miro Bezjak <bezjak.miro@gmail.com>
License MIT: http://www.opensource.org/licenses/mit-license.php
Documentation & source code: http://github.com/mbezjak/napalm

NAPALM_HOME = $NAPALM_HOME
EOF

exit 0
}

# print functions #
###################

#################
# program start #

while getopts "hv" option; do
  case $option in
    v) print_version ;;
    h) print_usage ;;
    *) print_usage ;;
  esac
done
shift $((OPTIND-1))


exit 0
